# Use a Python base image
FROM python:3-slim

# Set working directory
WORKDIR /backend

# Copy the requirements.txt and install dependencies
COPY ./requirements.txt ./
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy the source code into the container
COPY ./src ./src/

# Step 2: Expose the development server (default is port 80)
EXPOSE 80

# Run FastAPI with uvicorn in development mode (with --reload)
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]